run:
  timeout: 5m
  go: '1.24'

linters:
  enable:
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - govet
    - misspell
    - nakedret
    - copyloopvar
