# Server configuration
server:
  port: "8080"
  shutdown_timeout: "10s"  # Graceful shutdown timeout

# Rate limiting configuration
rate_limit:
  rate: "1500ms"        # Minimum time between requests (e.g., 1500ms for ~40 requests per minute)
  burst: 2              # Maximum number of requests in a burst
  max_concurrent: 3      # Maximum number of concurrent requests

# Logging configuration
logging:
  level: "info"   # debug, info, warn, error, fatal, panic
  format: "json"    # json or console

# Audiobookshelf configuration
audiobookshelf:
  url: "https://your-audiobookshelf-instance.com"
  token: "your-audiobookshelf-token"

# Hardcover configuration
hardcover:
  token: "your-hardcover-token"

# Application settings
app:
  sync_interval: "1h"
  minimum_progress: 0.01  # Minimum progress threshold (0.0 to 1.0)
  sync_want_to_read: true  # Sync books with 0% progress as "Want to Read"
  sync_owned: true        # Mark synced books as owned in Hardcover
  mismatch_output_dir: "./mismatches"  # Directory to store mismatch JSON files
  dry_run: false           # Enable dry run mode (no changes will be made)
  test_book_filter: ""    # Filter books by title for testing
  test_book_limit: 0       # Limit number of books to process for testing (0 = no limit)

# Sync configuration
sync:
  incremental: true
  state_file: "./data/sync_state.json"
  min_change_threshold: 60

# Paths configuration
paths:
  cache_dir: "./cache"    # Directory for cache files
