# Server configuration
server:
  port: "8080"
  shutdown_timeout: "10s"

# Rate limiting configuration (relaxed for tests)
rate_limit:
  rate: "100ms"
  burst: 10
  max_concurrent: 5

# Logging configuration
logging:
  level: "debug"
  format: "console"  # Use console format for test output

# Audiobookshelf configuration
audiobookshelf:
  url: "http://localhost:13378"
  token: "test-audiobookshelf-token"

# Hardcover configuration
hardcover:
  token: "test-hardcover-token"

# Application settings
app:
  debug: true
  sync_interval: "1h"
  minimum_progress: 0.01
  audiobook_match_mode: "loose"  # Use loose matching for tests
  sync_want_to_read: true
  sync_owned: true
  mismatch_output_dir: "./mismatches"
  dry_run: true  # Enable dry run for tests by default
  test_book_filter: ""
  test_book_limit: 5  # Limit to 5 books for testing

# File paths
paths:
  cache_dir: "./cache"
