# Server configuration
server:
  port: "8080"
  shutdown_timeout: "10s"  # Graceful shutdown timeout

# Rate limiting configuration
rate_limit:
  rate: "1500ms"        # Minimum time between requests (e.g., 1500ms for ~40 requests per minute)
  burst: 2              # Maximum number of requests in a burst
  max_concurrent: 3      # Maximum number of concurrent requests

# Logging configuration
logging:
  level: "info"   # debug, info, warn, error, fatal, panic
  format: "json"    # json or console

# Audiobookshelf configuration
audiobookshelf:
  url: "https://your-audiobookshelf-instance.com"
  token: "your-audiobookshelf-token"

# Hardcover configuration
hardcover:
  token: "your-hardcover-token"

# Application settings
app:
  test_book_filter: ""    # Filter books by title for testing
  test_book_limit: 0       # Limit number of books to process for testing (0 = no limit)

# Database configuration
# Supports SQLite (default), PostgreSQL, MySQL/MariaDB with automatic fallback
database:
  # Database type: sqlite, postgresql, mysql, mariadb
  type: "sqlite"
  
  # SQLite configuration (default)
  path: ""  # Uses default path if empty: ./data/database.db
  
  # PostgreSQL configuration (uncomment and configure for PostgreSQL)
  # host: "localhost"
  # port: 5432
  # name: "audiobookshelf_sync"
  # user: "sync_user"
  # password: ""  # Use environment variable DATABASE_PASSWORD for security
  # ssl_mode: "prefer"  # disable, allow, prefer, require, verify-ca, verify-full
  
  # MySQL/MariaDB configuration (uncomment and configure for MySQL)
  # host: "localhost"
  # port: 3306
  # name: "audiobookshelf_sync"
  # user: "sync_user"
  # password: ""  # Use environment variable DATABASE_PASSWORD for security
  
  # Connection pool settings (for PostgreSQL and MySQL)
  connection_pool:
    max_open_conns: 25      # Maximum number of open connections
    max_idle_conns: 5       # Maximum number of idle connections
    conn_max_lifetime: 60   # Connection lifetime in minutes

# Authentication Configuration
# Configure web UI authentication and user management
authentication:
  # Enable authentication system (default: false)
  # When disabled, web UI is accessible without login
  enabled: false
  
  # Session configuration
  session:
    # Secret for signing cookies (auto-generated if empty)
    # Use a strong, random secret for production
    secret: ""
    # Cookie name for sessions
    cookie_name: "audiobookshelf-sync-session"
    # Session max age in seconds (default: 86400 = 24 hours)
    max_age: 86400
    # Secure cookie - set to true for HTTPS deployments
    secure: false
    # HTTP only cookie (prevents JavaScript access)
    http_only: true
    # SameSite cookie policy (Strict, Lax, None)
    same_site: "Lax"
  
  # Default admin user (created automatically if auth is enabled)
  default_admin:
    # Default admin username
    username: "admin"
    # Default admin email
    email: "admin@localhost"
    # Default admin password (REQUIRED if auth is enabled)
    # Use environment variable AUTH_DEFAULT_ADMIN_PASSWORD for security
    password: ""
  
  # Keycloak/OIDC authentication (optional)
  keycloak:
    # Enable Keycloak/OIDC provider
    enabled: false
    # OIDC issuer URL (e.g., https://keycloak.example.com/realms/myrealm)
    issuer: ""
    # OIDC client ID
    client_id: ""
    # OIDC client secret (use environment variable for security)
    client_secret: ""
    # Redirect URI (must match Keycloak client config)
    redirect_uri: "http://localhost:8080/auth/callback"
    # OIDC scopes to request
    scopes: "openid profile email"
    # JWT claim containing user roles
    role_claim: "realm_access.roles"

# Sync configuration
sync:
  incremental: true
  state_file: "./data/sync_state.json"
  min_change_threshold: 60
  sync_interval: "1h"
  minimum_progress: 0.01  # Minimum progress threshold (0.0 to 1.0)
  sync_want_to_read: true  # Sync books with 0% progress as "Want to Read"
  sync_owned: true        # Mark synced books as owned in Hardcover
  dry_run: false           # Enable dry run mode (no changes will be made)

# Paths configuration
paths:
  data_dir: "./data"      # Base directory for application data (database, encryption keys, etc.)
  cache_dir: "./cache"    # Directory for cache files
  mismatch_output_dir: "./mismatches"  # Directory for mismatch reports
