# Server configuration
server:
  port: "8080"
  shutdown_timeout: "10s"  # Graceful shutdown timeout
  enable_web_ui: false  # Enable web UI for multi-user mode (default: false)

# Rate limiting configuration
rate_limit:
  rate: "1500ms"        # Minimum time between requests (e.g., 1500ms for ~40 requests per minute)
  burst: 2              # Maximum number of requests in a burst
  max_concurrent: 3      # Maximum number of concurrent requests

# Logging configuration
logging:
  level: "info"   # debug, info, warn, error, fatal, panic
  format: "json"    # json or console

# Audiobookshelf configuration
audiobookshelf:
  url: "https://your-audiobookshelf-instance.com"
  token: "your-audiobookshelf-token"

# Hardcover configuration
hardcover:
  token: "your-hardcover-token"

# Sync configuration
sync:
  # Enable incremental sync (only process changed books)
  incremental: true
  
  # Path to store sync state (default: ./data/sync_state.json)
  state_file: "./data/sync_state.json"
  
  # Minimum change in progress (seconds) to trigger an update (default: 60)
  min_change_threshold: 60
  
  # Sync interval (default: 1h)
  sync_interval: "1h"
  
  # Minimum progress threshold (0.0 to 1.0) - books with less progress will be skipped
  minimum_progress: 0.01
  
  # Sync books with 0% progress as "Want to Read" in Hardcover
  sync_want_to_read: true
  
  # Process books with 0% progress for mismatches and "want to read" status
  process_unread_books: false
  
  # Mark synced books as owned in Hardcover
  sync_owned: true
  
  # Enable dry run mode (no changes will be made)
  dry_run: false
  
  # Filter books by title for testing (regex pattern)
  test_book_filter: ""
  
  # Limit number of books to process for testing (0 = no limit)
  test_book_limit: 0
  
  # Library filtering configuration
  libraries:
    # Include only these libraries (empty = all)
    include: []
    # Exclude these libraries (empty = none)
    exclude: []

# Application settings (deprecated - use 'sync' section above)
app:
  # Deprecated: These settings are moved to the 'sync' section and will be removed in a future version
  sync_want_to_read: true  # Deprecated: Use sync.sync_want_to_read
  sync_owned: true        # Deprecated: Use sync.sync_owned
  dry_run: false          # Deprecated: Use sync.dry_run
  
  # Filter books by title for testing (deprecated - use sync.test_book_filter)
  test_book_filter: ""
  
  # Limit number of books to process for testing (deprecated - use sync.test_book_limit)
  test_book_limit: 0

# Database configuration
# Supports SQLite (default), PostgreSQL, MySQL/MariaDB with automatic fallback
database:
  # Database type: sqlite, postgresql, mysql, mariadb
  type: "sqlite"
  
  # SQLite configuration (default)
  path: ""  # Uses default path if empty: ./data/database.db
  
  # PostgreSQL configuration (uncomment and configure for PostgreSQL)
  # host: "localhost"
  # port: 5432
  # name: "audiobookshelf_sync"
  # user: "sync_user"
  # password: ""  # Use environment variable DATABASE_PASSWORD for security
  # ssl_mode: "prefer"  # disable, allow, prefer, require, verify-ca, verify-full
  
  # MySQL/MariaDB configuration (uncomment and configure for MySQL)
  # host: "localhost"
  # port: 3306
  # name: "audiobookshelf_sync"
  # user: "sync_user"
  # password: ""  # Use environment variable DATABASE_PASSWORD for security
  
  # Connection pool settings (for PostgreSQL and MySQL)
  connection_pool:
    max_open_conns: 25      # Maximum number of open connections
    max_idle_conns: 5       # Maximum number of idle connections
    conn_max_lifetime: 60   # Connection lifetime in minutes

# Authentication Configuration
# Configure web UI authentication and user management
authentication:
  # Enable authentication system (default: false)
  # When disabled, web UI is accessible without login
  enabled: false
  
  # Session configuration
  session:
    # Secret for signing cookies (auto-generated if empty)
    # Use a strong, random secret for production
    secret: ""
    # Cookie name for sessions
    cookie_name: "audiobookshelf-sync-session"
    # Session max age in seconds (default: 86400 = 24 hours)
    max_age: 86400
    # Secure cookie - set to true for HTTPS deployments
    secure: false
    # HTTP only cookie (prevents JavaScript access)
    http_only: true
    # SameSite cookie policy (Strict, Lax, None)
    same_site: "Lax"
  
  # Default admin user (created automatically if auth is enabled)
  default_admin:
    # Default admin username
    username: "admin"
    # Default admin email
    email: "admin@localhost"
    # Default admin password (REQUIRED if auth is enabled)
    # Use environment variable AUTH_DEFAULT_ADMIN_PASSWORD for security
    password: ""
  
  # Keycloak/OIDC authentication (optional)
  keycloak:
    # Enable Keycloak/OIDC provider
    enabled: false
    # OIDC issuer URL (e.g., https://keycloak.example.com/realms/myrealm)
    issuer: ""
    # OIDC client ID
    client_id: ""
    # OIDC client secret (use environment variable for security)
    client_secret: ""
    # Redirect URI (must match Keycloak client config)
    redirect_uri: "http://localhost:8080/auth/callback"
    # OIDC scopes to request
    scopes: "openid profile email"
    # JWT claim containing user roles
    role_claim: "realm_access.roles"



# Paths configuration
paths:
  data_dir: "./data"      # Base directory for application data (database, encryption keys, etc.)
  cache_dir: "./cache"    # Directory for cache files
  mismatch_output_dir: "./mismatches"  # Directory for mismatch reports
