name: Security Scan

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # Weekly scan

permissions:
  contents: read
  security-events: write

jobs:
  trivy-container-scan:
    name: Container Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image for scan (single arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          platforms: linux/amd64
          tags: local/abs-hardcover-sync:trivy-scan

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: local/abs-hardcover-sync:trivy-scan
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: 1
          ignore-unfixed: true
          vuln-type: 'os,library'
          scanners: 'vuln,misconfig,secret'

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

  trivy-fs-scan:
    name: Filesystem Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy filesystem scanner (debug output)
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          output: ''
          severity: 'CRITICAL,HIGH'
          exit-code: 0
          ignore-unfixed: true
          scanners: 'misconfig,secret'  # Use misconfig instead of deprecated config
          vuln-type: ''  # Explicitly disable vulnerability scanning for filesystem scan

      - name: Run Trivy filesystem scanner (SARIF output)
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-fs-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: 1
          ignore-unfixed: true
          scanners: 'misconfig,secret'  # Use misconfig instead of deprecated config
          vuln-type: ''  # Explicitly disable vulnerability scanning for filesystem scan

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-fs-results.sarif'
