name: Security Scan

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # Weekly scan

permissions:
  contents: read
  security-events: write

jobs:
  trivy-container-scan:
    name: Container Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image for scan (single arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          platforms: linux/amd64
          tags: local/abs-hardcover-sync:trivy-scan

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: local/abs-hardcover-sync:trivy-scan
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: 1
          ignore-unfixed: true
          vuln-type: 'os,library'
          scanners: 'vuln,misconfig,secret'

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

  trivy-fs-scan:
    name: Filesystem Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run Trivy filesystem scanner
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-fs-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: 0
          ignore-unfixed: true
          scanners: 'misconfig,secret'
          skip-files: '**/*.md,**/*.txt,**/*.json,**/go.sum,**/go.mod'
          skip-dirs: '.git,.github/workflows'
          trivyignores: '.trivyignore'

      - name: Check for vulnerabilities in SARIF results
        run: |
          if [ -f "trivy-fs-results.sarif" ]; then
            # Check if SARIF contains any actual vulnerabilities
            vuln_count=$(jq '.runs[0].results | length' trivy-fs-results.sarif 2>/dev/null || echo "0")
            if [ "$vuln_count" -gt 0 ]; then
              echo "❌ Security vulnerabilities found: $vuln_count"
              echo "📋 Vulnerability details:"
              jq -r '.runs[0].results[] | "- \(.ruleId): \(.message.text) (\(.locations[0].physicalLocation.artifactLocation.uri))"' trivy-fs-results.sarif || echo "Could not parse vulnerability details"
              echo "Please review the SARIF results and address the security issues."
              exit 1
            else
              echo "✅ No security vulnerabilities found - scan passed!"
            fi
          else
            echo "⚠️  SARIF file not found, but continuing..."
          fi

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-fs-results.sarif'
